# Generated by Django 2.0.7 on 2018-07-31 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ormModel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='id',
            new_name='key',
        ),
    ]
