# Generated by Django 2.0.7 on 2018-08-02 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoTemplate', '0001_initial'),
        ('ormModel', '0003_auto_20180802_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoTemplate.FrontUser'),
        ),
    ]
