# Generated by Django 2.0.7 on 2018-08-02 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ormModel', '0008_auto_20180802_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
    ]
